name: nextjs_to_ced

env:
  CED_ENVIRONMENT: development
  CED_CLI_TOKEN: ${{secrets.MERTHIN_CLI_TOKEN}}
  CED_PROJECT_PATH: packages/sdk-nextjs

on:
  push:
    branches:
      - main
    paths:
      - 'packages/sdk-nextjs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: MerthinTechnologies/push-ced-source-action@v1
